### ISSUE TITLE
signature on APK for v2.6.4 is broken

### ISSUE THREAD

**Issue by IzzySoft** [zjn0505/Xkcd-Android#13]
Looks like something went wrong with signing, could you please check?

```
$ apksigner verify xkcd-release.apk|grep -v WARN
DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: Malformed additional attribute #1
```

**Comment by IzzySoft** [comment]
Very same issue now for v2.6.6.

**Comment by zjn0505** [comment]
I'm not a pro on this.  I ran `apksigner verify -v --print-certs xkcd-2.6.6.apk` and got the following prints.
```
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true
Number of signers: 1
Signer #1 certificate DN: CN=Jienan Zhang, L=Shenyang, ST=Liaoning, C=CN
Signer #1 certificate SHA-256 digest: 8fc5bf4d7286475bba09879d3bee06757fb9843646080681ba723c7cf55a94b7
Signer #1 certificate SHA-1 digest: 8d9f358be8a1ec37c7f178de85dbf176384901d6
Signer #1 certificate MD5 digest: caffe22a001441d133233672734171bb
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
Signer #1 public key SHA-256 digest: 8b287f4dfd138de5c6a79ac069c194acb411171883713bb6f344b0fbd1b2110d
Signer #1 public key SHA-1 digest: 3ad629acc83192c453bd9249b57aaa1466e04a0a
Signer #1 public key MD5 digest: 8deb8f807fd5e10f000ecdcce73b805e
```
I don't know there we already have v3 scheme. This is printed from 29.0.0 SDK build-tools on mac.

Could this question be related?
https://stackoverflow.com/questions/54782328/apksigner-does-not-verify-signature

**Comment by IzzySoft** [comment]
Yes, that looks like it. And it seems your version of apksigner must be different (newer?) from mine, as must the one from SO: I don't get those details from `-v` or `--verbose`.

Additional note: apart from `apksigner` spitting out that error, there seem to be no further implications – which confirms the answer at SO that the issue is not with the APK but with apksigner itself.

Reading between the lines: we seem to use a version of `apksigner` that doesn't yet know to deal with v3 signatures – and thus tries them as v2, which fails as expected (as they are no v2).

So, possible work-arounds:

a) you do not sign v3 yet
b) me ignores the `apksigner` complaint

I say we go with b) here :laughing: If you agree, simply close this. Not much else the two of us can do about it.

Thanks a lot for investigating and finding the culprit! Now I just need to see how I can avoid it marking [your app](https://apt.izzysoft.de/fdroid/index/apk/xyz.jienan.xkcd) with `KnownVuln` and `DisabledAlgorithm` (caused by this). Easiest approach to that would be if you could provide a FOSS flavor coming without the proprietary stuff (GMS, Firebase, Firebase Analytics, Crashlytics) and we could get your app into the official [F-Droid](https://f-droid.org/) repo: there it would be built from source and signed by F-Droid, thus conforming with the `apksigner` version in use…

**Comment by IzzySoft** [comment]
PS:

c) me updates to the latest `apksigner` (v0.9) locally

Problem solved :tada:

Good pointer you found with that SO post, thanks a lot!

Still open to help you bringing your app to the official repo, if you need assistance with the "getting listed" part. I'm no Android dev, so I cannot help you with the "creating the flavor" part, sadly.

**Comment by zjn0505** [comment]
Thank you for the feedbacks and your articles on privacy. I've been a "good student" on following Android guidelines, like kept everything up-to-date. The `apksigner` I used in the post is from SDK 29.0.0, and apks were built from 3.5.0 Android build tools which I think brought in v3 scheme signature.

I haven't dove into F-Droid quite much before. It will be very meaningful and challenging for me to have a fully open-sourced app enlist in it.

**Comment by IzzySoft** [comment]
As a non-dev, it seems I wasn't that up-to-date – still sitting on the 28.x stuff here, which I just now updated to 29.x (so this issue served as a kick in the… well, reminder to update again :rofl:

Thanks for your kind words on my articles! There's a series on F-Droid included with them which might be useful to get you started: part 1 is a general intro, mostly targeted at the average user, part 2 for the advanced user and the developer, and part 3 for those who want to host their own repos easily. They are not "in-depths studies", but will give the reader a general overview – which (for users) mostly suffices. For the developer it should give the foundation to build upon, and knowing the raw where-abouts. You can find the series [here](https://android.izzysoft.de/articles/named/fdroid-intro) (linked page lists the URLs to the 3 parts).

If you need my assistance in the "getting-listed process", just call out! I'm one of the F-Droid maintainers, so I should be able to help (and where not, to know whom to call upon).

**Comment by zjn0505** [comment]
Thank you for the guidance. I've created a project [#2](https://github.com/zjn0505/Xkcd-Android/projects/2) to fully open-source this app and for enrolling it into F-Droid. Hopefully, meet you there soon.

**Comment by IzzySoft** [comment]
Cool, thanks! I won't be able to actively follow (I'm already drowning in tasks), but if there's something you think I (as non-developer) can help out with, feel free to ping me. I have no idea how to interact with those cards, though…

Note on the cards:

* **Push notififications.** There are some articles on how e.g. Tutanota implemented them in a FOSS way. I vaguely remember there are two libraries/frameworks available for that as well. I further remember approaches were made via XMPP/Jabber and via IMAP. That's all bread-crumbs, but the keywords might help you.
* **Signatures.** Yes, there will be conflicts: F-Droid uses its own keys to sign their builds. There are ways to make the packages compatible, but that's rather complex and to my knowledge currently only used by 3 apps. Keyword again: reproducible builds (short explanation: using the "same environments", the app built by you and the one built by F-Droid are, except for the signatures, "binary identical". That verified, *your* APK would be published by F-Droid)
* **Possibility of FOSS compliance.** Try to get as close as possible first. My scanner will tell rawly when it might fit (i.e. it doesn't detect a non-fitting library – and you can watch the progess [behind this link](https://apt.izzysoft.de/fdroid/index/apk/xyz.jienan.xkcd), just toggle the "libraries" section to see which are marked with a ⒹⓃⓉ). That point reached, apply for inclusion at the official repo; the scanner there and our packagers will check the remains, and our packagers can help you should there be any blockers.

PS: I guess it would be a good idea to *not* continue discussing this in this issue. I'd suggest opening separate issues for each "segment". That way, items can be processed separately, while still approaching the "big image".

Thanks for taking up the challenge! If you get stuck with something, I might start another of my famous "call-outs" at Mastodon, that worked well in the past :smile:
