### ISSUE TITLE
Fastlane changelogs

### ISSUE THREAD

**Issue by IzzySoft** [zjn0505/xkcd-Android#19]
According to Fastlane specs, names of the changelogs must reflect `versionCode` – you currently have them corresponding to `versionName`. So the current `2.7.7.txt` should rather be named `70.txt`. Could you please fix that (at least for the current and future ones)? Thanks!

**Comment by zjn0505** [comment]
Hi, thanks for reminding me.
It looks they changed the spec from `versionName` to `versionCode`.
https://github.com/fastlane/fastlane/commit/7d3c9434e90de30402edf82f3be91b25834bea0d

I will update the repository. Thank you.

**Comment by IzzySoft** [comment]
What, only this April? Strange. At F-Droid we've always used it that way AFAIR. And that's at least a couple of years. Looks like that was a "reverse direction" change: everyone used it that way, only they didn't notice :rofl: Quoting the commit message: "Google Play expects changelog files to be named for the version code to which they will be applied". Funny stuff…

But however: seeing what versionNames some projects use, sticking to versionCode for this is a very good thing. So thanks for picking this up! As your fastlane structure already reflects this, I'll close this issue now.

**Comment by IzzySoft** [comment]
PS: if you'd insert an empty line before the bullet point list in `full_description.txt`, it would be valid Markdown and render better in clients supporting that :wink:

```markdown
 This app has so far:

 - the best support to all those large xkcd comics. e.g. No. 657, 1040, and the toughest No. 980.
 - native support for interactive comics like 1608, 2198, etc
```

**Comment by zjn0505** [comment]
OK, I think the reason behind this is I'm not actually using fastlane supply to maintain store presence, only to pull it from play store to fill into this repository.
So all I did was `fastlane supply init`, then everything like duplicated screenshots, description were there.

**Comment by IzzySoft** [comment]
No offense meant – apologies if it sounded like! Just wanted to leave some pointers for improvement. Working with that on a daily base (I'm a maintainer at F-Droid, and also run my own repo), one gets an eye for such things :wink:
