### ISSUE TITLE
Title text renders incorrectly

### ISSUE THREAD

**Issue by vguttmann** [zjn0505/xkcd-Android#22]
The title text of some comics such as [1942](https://xkcd.com/1942) or [1943](https://xkcd.com/1943) renders incorrectly.

**Comment by zjn0505** [comment]
This is a bug in my xkcd crawler. https://github.com/zjn0505/xkcd/issues/6
It failed to parse characters like what's in https://xkcd.com/1943/info.0.json
I have corrected 1942 and 1943 in my cloud database. but on client side, the error will remain until clear app data.

**Comment by vguttmann** [comment]
Ah, then I'll do that. Thanks for explaining, and thanks for developing this awesome app! I wrote a mail with some other stuff I found to you pay store gmail, but won't add it here, since an "Issues: 0" on the GitHub page is immensely satisfying.
