### ISSUE TITLE
Comic #1056 Displays Wrong Image

### ISSUE THREAD

**Issue by MetaNite64** [zjn0505/xkcd-Android#24]
Comic #1056 displays the image for comic #1506, xkcloud, instead of the proper comic, Felidae. The inverse is not true, xkcloud displays correctly. Additionally, it's only the image; the correct title, title text, and explainxkcd article are all there. This seems to be the only instance of a typo like that.

**Comment by zjn0505** [comment]
Thanks. I found it is also wrong in my cloud database. I've fixed it there.
On the application side, this cannot be hot fixed, as the wrong image is persisted in local database. A fresh install or application data clear should make it correct.

Sorry for the mistake. Thanks for pointing it out.
