### ISSUE TITLE
Latest Update (3/2022)

### ISSUE THREAD

**Issue by pastorlarry** [zjn0505/xkcd-Android#26]
Update will not install. ![Screenshot_20220310-161003-375.png](https://user-images.githubusercontent.com/37308396/157763357-7cae2445-4a1a-4e97-9ece-38e1c1ac6251.png)

**Comment by zjn0505** [comment]
The minSdk version is 16, hasn't been changed for last 4 years.
May I ask which store it is? The icon looks like f-droid but I haven't managed to get the app accepted there.

**Comment by pastorlarry** [comment]
Hi!

I installed the app from F-Droid (and LOVE IT!), and it keeps saying I've an update, but you see what happens when I try to download it. I am NOT tech savvy on the "code" side of things, so I figured I'd submit something about my issue.

Thanks!

Larry

Mar 10, 2022 5:11:05 PM zjn0505 ***@***.***>:

**Comment by zjn0505** [comment]
Got it. I will fix it asap.
Actually this app isn't accepted by the official F-Droid collection, as far as I know only IzzySoft has added the app to his collection at https://apt.izzysoft.de/fdroid/index/apk/xyz.jienan.xkcd.

**Comment by pastorlarry** [comment]
Ahhh. I must have gotten it when I added repositories. I'm VERY new to all of this stuff. I'm thinking about taking some coding courses so technology doesn't leave me further behind. I feel ancient at only 44 years old!

Mar 10, 2022 8:19:42 PM zjn0505 ***@***.***>:

**Comment by zjn0505** [comment]
Should be resolved in the new release 2.7.10.

https://github.com/zjn0505/xkcd-Android/releases/tag/xkcd_2.7.10

**Comment by zjn0505** [comment]
Close this issue.
https://apt.izzysoft.de/fdroid/index/apk/xyz.jienan.xkcd is not updated there yet.
