### ISSUE TITLE
Comic #2408 ExplainXKCD Fails to Display

### ISSUE THREAD

**Issue by MetaNite64** [zjn0505/xkcd-Android#29]
The comic in question, Egg Strategies, has a perfectly good ExplainXKCD article. However, the page uses the header "Eggsplanation" above the comic explanation. I suspect that the app is only looking for the standard "Explanation" header, and failing to display anything when the header isn't found.

**Comment by zjn0505** [comment]
Thanks.

Fixed in https://github.com/zjn0505/xkcd-Android/commit/fe4209c9a270b07867be8a2e8f7f94384c8065ca, adding a fallback when "Explanation" header not found.
