### ISSUE TITLE
Option to disable push notifications.

### ISSUE THREAD

**Issue by akt1n4** [zjn0505/xkcd-Android#32]
I wish to have my notifications panel cluster-free, and I think its better to disable push notifications for new xkcd arrivals rather than via Android settings as I might miss some important notifications from the app otherwise. If using the Android settings is a better option, I an fine with it too.

(P.s : I like your app and find it hassle-free along with the offline and explainxkcd feature)

On a side note, having an about section in settings would be nice as it can have a github direct link.

**Comment by zjn0505** [comment]
If your phone is Android 8.0 above. The perferred option is to use Android notification channels to manage notification of an app.

There are 2 channels used in this app: `xkcd` and `what if` to send notification to when there is an update.

You can go to the App info page of this app in Android settings, at the bottom there is a section called notification category.

<img width=300 src="https://user-images.githubusercontent.com/6925920/191904095-ba6d0544-45cc-4073-9d03-ffea774f5fbe.png"/>

You can disable the channel of `xkcd` from there.

By doing so notifications from other apps won't be interrupted.

This is the most preferred option to me to manage app notification.

Even if I would add a notification control settings, I would redirect it to this page to let you turn it on/off from there.

Thanks for your likes and the "About" section suggestion.

**Comment by zjn0505** [comment]
Android 13 will require notification permission is default to be OFF and need to be explicitly requested.
