### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by Sayanel01** [zjn0505/xkcd-Android#33]
On comic 971, the title text does not display correctly

See 
![Screenshot_20230108-172054](https://user-images.githubusercontent.com/17898277/211207847-017119f7-4ca4-478f-9e74-33d48e2ba1a4.png)

I did not encounter this on any other comic

**Comment by zjn0505** [comment]
Thank you. I know there are several comics having this problem.

This one can be found at https://xkcd.com/971/info.0.json where the apostrophe is encoded as `\u00e2\u0080\u0099`.

I am not a pro in encoding, and only did a little research on how to handle it, but still no results.

**Comment by zjn0505** [comment]
I've updated it from my cloud xkcd storage.

If you go to "Settings -> Storage Management -> xkcd comics -> DELETE INFO".

It will help to rebuild the local info storage and fix the problem.

**Comment by Sayanel01** [comment]
It's fixed on my side too
Thanks

**Comment by Sayanel01** [comment]
I found another : title of 1053 showing of as
"Theâ€‰bacon"

While possible to fixes these case by case, is there no faster method?

**Comment by Sayanel01** [comment]
Another in 1147 title text, PokÃ©Mon

**Comment by zjn0505** [comment]
Thank you.

I've updated both and also made a database query and found another 2 comics with issues and have them fixed.

I think it is possible to decode properly, I know another actively maintained xkcd app has made it.

https://github.com/tom-anders/Easy_xkcd/pull/157

The quickest thing for now is to correct case by case. I will look into it in the future.
